/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as SponsorRouteRouteImport } from './routes/_sponsor/route'
import { Route as SponsorsRouteImport } from './routes/sponsors'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as SponsorSponsorRouteImport } from './routes/_sponsor/sponsor'
import { Route as SponsorsResetPasswordRouteImport } from './routes/sponsors.reset-password'
import { Route as AuthenticatedAdminMembersRouteImport } from './routes/_authenticated/admin.members'
import { Route as SponsorSponsorIndexRouteImport } from './routes/_sponsor/sponsor.index'
import { Route as SponsorSponsorMembersRouteImport } from './routes/_sponsor/sponsor.members'
import { Route as SponsorSponsorPerksRouteImport } from './routes/_sponsor/sponsor.perks'
import { Route as SponsorSponsorResumesRouteImport } from './routes/_sponsor/sponsor.resumes'
import { Route as AuthenticatedAdminCategoriesIndexRouteImport } from './routes/_authenticated/admin.categories.index'
import { Route as AuthenticatedAdminCategoriesCategoryIdRouteImport } from './routes/_authenticated/admin.categories.$categoryId'
import { Route as AuthenticatedAdminSponsorsIndexRouteImport } from './routes/_authenticated/admin.sponsors.index'
import { Route as AuthenticatedAdminSponsorsSponsorSlugRouteImport } from './routes/_authenticated/admin.sponsors.$sponsorSlug'
import { Route as SponsorSponsorResumesCategoryIdRouteImport } from './routes/_sponsor/sponsor.resumes.$categoryId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const SponsorRouteRoute = SponsorRouteRouteImport.update({
  id: '/_sponsor',
  getParentRoute: () => rootRouteImport,
} as any)
const SponsorsRoute = SponsorsRouteImport.update({
  id: '/sponsors',
  path: '/sponsors',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const SponsorSponsorRoute = SponsorSponsorRouteImport.update({
  id: '/sponsor',
  path: '/sponsor',
  getParentRoute: () => SponsorRouteRoute,
} as any)
const SponsorsResetPasswordRoute = SponsorsResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => SponsorsRoute,
} as any)
const AuthenticatedAdminMembersRoute =
  AuthenticatedAdminMembersRouteImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const SponsorSponsorIndexRoute = SponsorSponsorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SponsorSponsorRoute,
} as any)
const SponsorSponsorMembersRoute = SponsorSponsorMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => SponsorSponsorRoute,
} as any)
const SponsorSponsorPerksRoute = SponsorSponsorPerksRouteImport.update({
  id: '/perks',
  path: '/perks',
  getParentRoute: () => SponsorSponsorRoute,
} as any)
const SponsorSponsorResumesRoute = SponsorSponsorResumesRouteImport.update({
  id: '/resumes',
  path: '/resumes',
  getParentRoute: () => SponsorSponsorRoute,
} as any)
const AuthenticatedAdminCategoriesIndexRoute =
  AuthenticatedAdminCategoriesIndexRouteImport.update({
    id: '/categories/',
    path: '/categories/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCategoriesCategoryIdRoute =
  AuthenticatedAdminCategoriesCategoryIdRouteImport.update({
    id: '/categories/$categoryId',
    path: '/categories/$categoryId',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSponsorsIndexRoute =
  AuthenticatedAdminSponsorsIndexRouteImport.update({
    id: '/sponsors/',
    path: '/sponsors/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSponsorsSponsorSlugRoute =
  AuthenticatedAdminSponsorsSponsorSlugRouteImport.update({
    id: '/sponsors/$sponsorSlug',
    path: '/sponsors/$sponsorSlug',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const SponsorSponsorResumesCategoryIdRoute =
  SponsorSponsorResumesCategoryIdRouteImport.update({
    id: '/$categoryId',
    path: '/$categoryId',
    getParentRoute: () => SponsorSponsorResumesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sponsors': typeof SponsorsRouteWithChildren
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/sponsor': typeof SponsorSponsorRouteWithChildren
  '/sponsors/reset-password': typeof SponsorsResetPasswordRoute
  '/admin/members': typeof AuthenticatedAdminMembersRoute
  '/sponsor/members': typeof SponsorSponsorMembersRoute
  '/sponsor/perks': typeof SponsorSponsorPerksRoute
  '/sponsor/resumes': typeof SponsorSponsorResumesRouteWithChildren
  '/sponsor/': typeof SponsorSponsorIndexRoute
  '/admin/categories/$categoryId': typeof AuthenticatedAdminCategoriesCategoryIdRoute
  '/admin/sponsors/$sponsorSlug': typeof AuthenticatedAdminSponsorsSponsorSlugRoute
  '/sponsor/resumes/$categoryId': typeof SponsorSponsorResumesCategoryIdRoute
  '/admin/categories/': typeof AuthenticatedAdminCategoriesIndexRoute
  '/admin/sponsors/': typeof AuthenticatedAdminSponsorsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sponsors': typeof SponsorsRouteWithChildren
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/sponsors/reset-password': typeof SponsorsResetPasswordRoute
  '/admin/members': typeof AuthenticatedAdminMembersRoute
  '/sponsor/members': typeof SponsorSponsorMembersRoute
  '/sponsor/perks': typeof SponsorSponsorPerksRoute
  '/sponsor/resumes': typeof SponsorSponsorResumesRouteWithChildren
  '/sponsor': typeof SponsorSponsorIndexRoute
  '/admin/categories/$categoryId': typeof AuthenticatedAdminCategoriesCategoryIdRoute
  '/admin/sponsors/$sponsorSlug': typeof AuthenticatedAdminSponsorsSponsorSlugRoute
  '/sponsor/resumes/$categoryId': typeof SponsorSponsorResumesCategoryIdRoute
  '/admin/categories': typeof AuthenticatedAdminCategoriesIndexRoute
  '/admin/sponsors': typeof AuthenticatedAdminSponsorsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_sponsor': typeof SponsorRouteRouteWithChildren
  '/sponsors': typeof SponsorsRouteWithChildren
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_sponsor/sponsor': typeof SponsorSponsorRouteWithChildren
  '/sponsors/reset-password': typeof SponsorsResetPasswordRoute
  '/_authenticated/admin/members': typeof AuthenticatedAdminMembersRoute
  '/_sponsor/sponsor/members': typeof SponsorSponsorMembersRoute
  '/_sponsor/sponsor/perks': typeof SponsorSponsorPerksRoute
  '/_sponsor/sponsor/resumes': typeof SponsorSponsorResumesRouteWithChildren
  '/_sponsor/sponsor/': typeof SponsorSponsorIndexRoute
  '/_authenticated/admin/categories/$categoryId': typeof AuthenticatedAdminCategoriesCategoryIdRoute
  '/_authenticated/admin/sponsors/$sponsorSlug': typeof AuthenticatedAdminSponsorsSponsorSlugRoute
  '/_sponsor/sponsor/resumes/$categoryId': typeof SponsorSponsorResumesCategoryIdRoute
  '/_authenticated/admin/categories/': typeof AuthenticatedAdminCategoriesIndexRoute
  '/_authenticated/admin/sponsors/': typeof AuthenticatedAdminSponsorsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sponsors'
    | '/admin'
    | '/onboarding'
    | '/profile'
    | '/sponsor'
    | '/sponsors/reset-password'
    | '/admin/members'
    | '/sponsor/members'
    | '/sponsor/perks'
    | '/sponsor/resumes'
    | '/sponsor/'
    | '/admin/categories/$categoryId'
    | '/admin/sponsors/$sponsorSlug'
    | '/sponsor/resumes/$categoryId'
    | '/admin/categories/'
    | '/admin/sponsors/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sponsors'
    | '/admin'
    | '/onboarding'
    | '/profile'
    | '/sponsors/reset-password'
    | '/admin/members'
    | '/sponsor/members'
    | '/sponsor/perks'
    | '/sponsor/resumes'
    | '/sponsor'
    | '/admin/categories/$categoryId'
    | '/admin/sponsors/$sponsorSlug'
    | '/sponsor/resumes/$categoryId'
    | '/admin/categories'
    | '/admin/sponsors'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_sponsor'
    | '/sponsors'
    | '/_authenticated/admin'
    | '/_authenticated/onboarding'
    | '/_authenticated/profile'
    | '/_sponsor/sponsor'
    | '/sponsors/reset-password'
    | '/_authenticated/admin/members'
    | '/_sponsor/sponsor/members'
    | '/_sponsor/sponsor/perks'
    | '/_sponsor/sponsor/resumes'
    | '/_sponsor/sponsor/'
    | '/_authenticated/admin/categories/$categoryId'
    | '/_authenticated/admin/sponsors/$sponsorSlug'
    | '/_sponsor/sponsor/resumes/$categoryId'
    | '/_authenticated/admin/categories/'
    | '/_authenticated/admin/sponsors/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  SponsorRouteRoute: typeof SponsorRouteRouteWithChildren
  SponsorsRoute: typeof SponsorsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_sponsor': {
      id: '/_sponsor'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SponsorRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sponsors': {
      id: '/sponsors'
      path: '/sponsors'
      fullPath: '/sponsors'
      preLoaderRoute: typeof SponsorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_sponsor/sponsor': {
      id: '/_sponsor/sponsor'
      path: '/sponsor'
      fullPath: '/sponsor'
      preLoaderRoute: typeof SponsorSponsorRouteImport
      parentRoute: typeof SponsorRouteRoute
    }
    '/sponsors/reset-password': {
      id: '/sponsors/reset-password'
      path: '/reset-password'
      fullPath: '/sponsors/reset-password'
      preLoaderRoute: typeof SponsorsResetPasswordRouteImport
      parentRoute: typeof SponsorsRoute
    }
    '/_authenticated/admin/members': {
      id: '/_authenticated/admin/members'
      path: '/members'
      fullPath: '/admin/members'
      preLoaderRoute: typeof AuthenticatedAdminMembersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_sponsor/sponsor/': {
      id: '/_sponsor/sponsor/'
      path: '/'
      fullPath: '/sponsor/'
      preLoaderRoute: typeof SponsorSponsorIndexRouteImport
      parentRoute: typeof SponsorSponsorRoute
    }
    '/_sponsor/sponsor/members': {
      id: '/_sponsor/sponsor/members'
      path: '/members'
      fullPath: '/sponsor/members'
      preLoaderRoute: typeof SponsorSponsorMembersRouteImport
      parentRoute: typeof SponsorSponsorRoute
    }
    '/_sponsor/sponsor/perks': {
      id: '/_sponsor/sponsor/perks'
      path: '/perks'
      fullPath: '/sponsor/perks'
      preLoaderRoute: typeof SponsorSponsorPerksRouteImport
      parentRoute: typeof SponsorSponsorRoute
    }
    '/_sponsor/sponsor/resumes': {
      id: '/_sponsor/sponsor/resumes'
      path: '/resumes'
      fullPath: '/sponsor/resumes'
      preLoaderRoute: typeof SponsorSponsorResumesRouteImport
      parentRoute: typeof SponsorSponsorRoute
    }
    '/_authenticated/admin/categories/': {
      id: '/_authenticated/admin/categories/'
      path: '/categories'
      fullPath: '/admin/categories/'
      preLoaderRoute: typeof AuthenticatedAdminCategoriesIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/categories/$categoryId': {
      id: '/_authenticated/admin/categories/$categoryId'
      path: '/categories/$categoryId'
      fullPath: '/admin/categories/$categoryId'
      preLoaderRoute: typeof AuthenticatedAdminCategoriesCategoryIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/sponsors/': {
      id: '/_authenticated/admin/sponsors/'
      path: '/sponsors'
      fullPath: '/admin/sponsors/'
      preLoaderRoute: typeof AuthenticatedAdminSponsorsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/sponsors/$sponsorSlug': {
      id: '/_authenticated/admin/sponsors/$sponsorSlug'
      path: '/sponsors/$sponsorSlug'
      fullPath: '/admin/sponsors/$sponsorSlug'
      preLoaderRoute: typeof AuthenticatedAdminSponsorsSponsorSlugRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_sponsor/sponsor/resumes/$categoryId': {
      id: '/_sponsor/sponsor/resumes/$categoryId'
      path: '/$categoryId'
      fullPath: '/sponsor/resumes/$categoryId'
      preLoaderRoute: typeof SponsorSponsorResumesCategoryIdRouteImport
      parentRoute: typeof SponsorSponsorResumesRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminMembersRoute: typeof AuthenticatedAdminMembersRoute
  AuthenticatedAdminCategoriesCategoryIdRoute: typeof AuthenticatedAdminCategoriesCategoryIdRoute
  AuthenticatedAdminSponsorsSponsorSlugRoute: typeof AuthenticatedAdminSponsorsSponsorSlugRoute
  AuthenticatedAdminCategoriesIndexRoute: typeof AuthenticatedAdminCategoriesIndexRoute
  AuthenticatedAdminSponsorsIndexRoute: typeof AuthenticatedAdminSponsorsIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminMembersRoute: AuthenticatedAdminMembersRoute,
  AuthenticatedAdminCategoriesCategoryIdRoute:
    AuthenticatedAdminCategoriesCategoryIdRoute,
  AuthenticatedAdminSponsorsSponsorSlugRoute:
    AuthenticatedAdminSponsorsSponsorSlugRoute,
  AuthenticatedAdminCategoriesIndexRoute:
    AuthenticatedAdminCategoriesIndexRoute,
  AuthenticatedAdminSponsorsIndexRoute: AuthenticatedAdminSponsorsIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface SponsorSponsorResumesRouteChildren {
  SponsorSponsorResumesCategoryIdRoute: typeof SponsorSponsorResumesCategoryIdRoute
}

const SponsorSponsorResumesRouteChildren: SponsorSponsorResumesRouteChildren = {
  SponsorSponsorResumesCategoryIdRoute: SponsorSponsorResumesCategoryIdRoute,
}

const SponsorSponsorResumesRouteWithChildren =
  SponsorSponsorResumesRoute._addFileChildren(
    SponsorSponsorResumesRouteChildren,
  )

interface SponsorSponsorRouteChildren {
  SponsorSponsorMembersRoute: typeof SponsorSponsorMembersRoute
  SponsorSponsorPerksRoute: typeof SponsorSponsorPerksRoute
  SponsorSponsorResumesRoute: typeof SponsorSponsorResumesRouteWithChildren
  SponsorSponsorIndexRoute: typeof SponsorSponsorIndexRoute
}

const SponsorSponsorRouteChildren: SponsorSponsorRouteChildren = {
  SponsorSponsorMembersRoute: SponsorSponsorMembersRoute,
  SponsorSponsorPerksRoute: SponsorSponsorPerksRoute,
  SponsorSponsorResumesRoute: SponsorSponsorResumesRouteWithChildren,
  SponsorSponsorIndexRoute: SponsorSponsorIndexRoute,
}

const SponsorSponsorRouteWithChildren = SponsorSponsorRoute._addFileChildren(
  SponsorSponsorRouteChildren,
)

interface SponsorRouteRouteChildren {
  SponsorSponsorRoute: typeof SponsorSponsorRouteWithChildren
}

const SponsorRouteRouteChildren: SponsorRouteRouteChildren = {
  SponsorSponsorRoute: SponsorSponsorRouteWithChildren,
}

const SponsorRouteRouteWithChildren = SponsorRouteRoute._addFileChildren(
  SponsorRouteRouteChildren,
)

interface SponsorsRouteChildren {
  SponsorsResetPasswordRoute: typeof SponsorsResetPasswordRoute
}

const SponsorsRouteChildren: SponsorsRouteChildren = {
  SponsorsResetPasswordRoute: SponsorsResetPasswordRoute,
}

const SponsorsRouteWithChildren = SponsorsRoute._addFileChildren(
  SponsorsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  SponsorRouteRoute: SponsorRouteRouteWithChildren,
  SponsorsRoute: SponsorsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
